### ISSUE TITLE
Push Iterator hasNext blocks indefinitely

### ISSUE THREAD

**Issue by yschimke** [twitter/whiskey#9]
This is even when making a request that does not push any response

"main" prio=5 tid=0x00007f88fa80c000 nid=0x1103 waiting on condition [0x000000010c3a6000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007ef03f268> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.twitter.whiskey.futures.ReactiveFuture$StreamingIterator.hasNext(ReactiveFuture.java:221)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:41)
	at scala.collection.Iterator$class.toStream(Iterator.scala:1143)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toSeq(TraversableOnce.scala:261)
	at scala.collection.AbstractIterator.toSeq(Iterator.scala:1157)
	at com.twitter.twurl.clients.WhiskeyTwitterClient.makeTfeRequest(WhiskeyTwitterClient.scala:88)
	at com.twitter.twurl.Twurl$class.makeRequest(Twurl.scala:82)
	at com.twitter.twurl.TwurlMain$.makeRequest(TwurlMain.scala:3)
	at com.twitter.twurl.Twurl$class.appMain(Twurl.scala:46)
	at com.twitter.twurl.TwurlMain$.appMain(TwurlMain.scala:3)
	at com.twitter.inject.app.App$class.callAppMain(App.scala:140)
	at com.twitter.inject.app.App$class.main(App.scala:63)
	at com.twitter.twurl.TwurlMain$.main(TwurlMain.scala:3)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:167)
	at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:166)
	at scala.Option.foreach(Option.scala:236)
	at com.twitter.app.App$class.nonExitingMain(App.scala:166)
	at com.twitter.twurl.TwurlMain$.nonExitingMain(TwurlMain.scala:3)
	at com.twitter.app.App$class.main(App.scala:132)
	at com.twitter.twurl.TwurlMain$.main(TwurlMain.scala:3)
	at com.twitter.twurl.TwurlMain.main(TwurlMain.scala)

**Comment by yschimke** [comment]
I think I have confirmed it is fixed by adding the following line to RequestOperation

    void complete(int statusCode) {

        if (isDone()) throw new RuntimeException("operation already completed");
        finalizeStats();
        headersFuture.complete();
        bodyFuture.complete();
        pushFuture.complete(); // missing
        statsFuture.set(stats);
        try {
            set(new Response(statusCode, headersFuture.get(), bodyFuture.get(), stats));
        } catch (ExecutionException | InterruptedException e) {
            fail(e);
        }
    }
